### PR TITLE
Update README.md with installation instructions

### PR DESCRIPTION
**Pull request by kartikarora**
No installation instructions on README :( So I added it! :)

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks. Please change the readme installation to simply point to the website: saves having to keep installation instructions up-to-date in two places.

As for the website, please move the brew instructions inside the modal 👍

**Comment by kartikarora** [comment]
I've made the modal larger to incorporate 3 buttons in a row. On clicking the homebrew button, the command is copied to clipboard. On hover, it simply shows a tooltip.

image

**Comment by kartikarora** [comment]
Sorry for the train of commits, I was fixing the lint check errors. All good now! :)

**Comment by will-stone** [comment]
Thanks. I've updated it to put the install instruction inline. Although the copy button is quick, I think those who know about brew will naturally search for a cask first. Therefore, I've put the install command inline. Also, after recently reading about [the dangers of copy-pasting commands from the web](https://news.ycombinator.com/item?id=10554679), I'm a little reticent to add one to the page. Here's the updated look:

image

**Comment by kartikarora** [comment]
Fair enough. I agree with the web copy issues. I myself check things on boop before pasting anything copied from the web.

If I may, how did you fix the lint issue for GitHub workflow? I couldn't get the build to pass without eslint fixes.

**Comment by will-stone** [comment]
When you had jQuery? I used ‘window.$’. The eslint configuration lives in the package.json file. You can run it locally with ‘yarn lint’.

**Comment by kartikarora** [comment]
I see! Well, thanks for that! 🍻

**Comment by kartikarora** [comment]
Is there any other blocker for this PR?

**Comment by will-stone** [comment]
House move. DIY. Day job. Tiredness. The Undoing. Organising a bathroom refurb. Praying the shelves I put up don’t fall off the wall. Netflix. Assembling flat pack furniture. Washing. Cooking. Going for the odd walk. 

Oh, nothing really 😆 I’ll merge it now...

**Comment by kartikarora** [comment]
Ahaha, I get it. I just meant why one of the two checks isn't passing 😛 Should have been clearer.

Cheers!

**Comment by will-stone** [comment]
Ha 🙂 I think that macOS check doesn’t like branches 🤷‍♂️ But we know we’re not affecting the app code here so I just forced it through. Thanks for making Browserosaurus better 😁

**Pull request merged**
