### PR TITLE
WIP: Add support for Chrome Profiles

### PR DESCRIPTION
**Pull request by aakside**
* Added Chrome profiles to the browser picker making it possible to open
links in particular Chrome profiles.
* TODO: Fix labels in picker.
* TODO: Plan for and fix hotkeys.

### CODE REVIEW

**Comment by will-stone** [comment]
Nice 👍 I’m currently reevaluating B and how it works. Essentially I’m thinking of making it more of a browser _manager_ rather than a _picker_. Ideally this will include the ability to make plugins, which this functionality would ideally suit. It’s very early days yet but you can follow along on the *next* branch. 

My concern here is that this is very specific to Chrome and we would now have browser-specific code hardcoded into the app. With the new world, I’m hoping to have panels and an action-bar (think VSCode), where people can create their own panels (via plugins) to interact with actions and events. Therefore, there could be a whole panel dedicated to Chrome profiles, or Firefox profiles etc that isn’t part of the core app, but an addon instead. 

Like I said, very early days at the moment, I’ll let you know when it’s ready for alpha testing.

**Comment by aakside** [comment]
I like the idea of a Chrome profiles plugin and not having browser-specific code in this project.

Maybe with this hypothetical plugin, a user can be two keystrokes/clicks away from launching a particular browser profile after clicking a link. Maybe keyboard key(s) + click shortcuts can be user-assigned in a settings panel to later bypass the UI if desired.

Sounds exciting! Can't wait to hear back and see how it has progressed!

**Comment by aakside** [comment]
I also feel a little silly because I just noticed there was an issue, with work, for Chrome profiles 😳

**Comment by will-stone** [comment]
No need to feel silly; hopefully we can combine all the efforts. Yes, shortcut changing has been a requested feature before so I do have this in mind. The new app will be a dedicated window rather than a fake picker window, therefore keyboard shortcuts will be very important as it will no longer open next to the mouse. Anyway, long way to go yet, but I’m looking forward to getting to a point where I can start asking fellow devs to take a look 😊

**Comment by will-stone** [comment]
I'm gonna close this as the code has changed considerably since this was opened. Feel free to submit another PR for Chrome Profile support, but with all the changes I've made it's probably best to simply start again. Thanks.

**Pull request closed without merging**
