### PR TITLE
Figma

### PR DESCRIPTION
**Pull request by JanOstrowka**
Better late than never ([original pull request](https://github.com/will-stone/browserosaurus/pull/423))!
This time it is a tested, fully working pull requested, which adds support for Figma.
<br>
Best regards,
Jan

### CODE REVIEW

**Comment by JanOstrowka** [comment]
I have also added support for [Yattee](https://github.com/yattee/yattee)

**Comment by will-stone** [comment]
Hi Jan. Thanks, a couple of things:

- Please remove and then add a gitignore entry for your IDE entries.
- Please only add support for one application per PR.

Cheers,

Will.

**Comment by JanOstrowka** [comment]
Hi @will-stone!

I believe it has been fixed now.
- I have updated and removed obsolete IDE files
- Yattee has been removed from this pull request
<br>
Best regards,
Jan

**Comment by will-stone** [comment]
Thanks @JanOstrowka, finally could you please rebase and squash your commits, thanks 🙂

**Comment by JanOstrowka** [comment]
I have never done that, but it might have just been successful.
<br>
Best regards,
Jan

**Comment by will-stone** [comment]
No worries. Can you please give me push rights to the branch and I'll rebase them for you. Thanks.

**Comment by will-stone** [comment]
There should be a "Allow edits by maintainers" checkbox on the page, at the bottom of the right sidebar.

**Comment by JanOstrowka** [comment]
> There should be a "Allow edits by maintainers" checkbox on the page, at the bottom of the right sidebar.

It is and has been enabled from the very begining.

**Comment by will-stone** [comment]
Oh, I couldn't get it to push my changes. No worries, I'll do a squash commit. Thanks.

**Pull request merged**
