### PR TITLE
feat: add official Twitter app from macOS AppStore

### PR DESCRIPTION
**Pull request by sfeuga**
Just add the [official Twitter app from macOS AppStore](https://apps.apple.com/jp/app/twitter/id1482454543?l=en&mt=12)

### CODE REVIEW

**Comment by will-stone** [comment]
Hi 👋 Thanks for the contribution. Can you please confirm you've tested this locally and it behaves as expected?

**Comment by sfeuga** [comment]
Hello, you are welcome!
Yes, for sure, I'll test again with the latest Twitter app, latest MacOS updated and latest build.

I'll confirm that to you in the next few days.

PS: Your app is so great it should be a default option in MacOS!
Thanks a lot!

**Comment by sfeuga** [comment]
I just tested with the NodeJS 18.6.0 and it working well.
I made a video using the local build.

https://user-images.githubusercontent.com/5821408/179973083-f19a5774-cb6f-4d60-a3bd-81811df4d0a9.mov

**Comment by will-stone** [comment]
Cool, resolve the conflict and this'll be good to go 🙂

**Pull request merged**
