### PR TITLE
User configuration sync

### PR DESCRIPTION
**Pull request by Jackymancs4**
Quoting:
> On load, userConfig is read. If userConfig file missing, defaultConfig is copied over. If userConfig available, the browser names are compared to defaultConfig, if any browser's missing in userConfig then these are appended to the userConfig array. If any in userConfig that aren't in defaultConfig then these are removed from userConfig. This completes the config sync.

### CODE REVIEW

**Comment by will-stone** [comment]
Could I have push access to the branch?

I find this works fine with `yarn start` but I get the following error when using the packaged app:

monosnap 2017-12-11 20-55-33

**Comment by Jackymancs4** [comment]
Well, I have very limited experience with permission management on github..

**Comment by will-stone** [comment]
Here's the instructions: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Jackymancs4** [comment]
The ```allow edits from maintainers``` was already on, (actually that's a default). I believed something else was necessary, but good to know.

For the packaging.. well no, nothing works!
I tried to change the packageManager to fix the error (it work and it make sense this way), but now It runs only in background..

**Comment by Jackymancs4** [comment]
Does your master get packaged fine?

**Comment by will-stone** [comment]
Yeah, my master works. Weird, don't know why I can't push to the pull-request. I'll look into that.

I tried downloading Node 6 and NPM 3 but that didn't work either. Maybe it's something to do with the new packages: mem-fs ?

**Comment by will-stone** [comment]
I can't for some reason push to this pull-request. I've put my changes in branch pr/17. Please either pull those in here or note the changes and make them manually.

This still doesn't solve our package problem though. I'll do some more investigation tomorrow.

**Comment by Jackymancs4** [comment]
I thought about it, too. Now, the whole point of my original idea of a JSON based configuration system that mirror a default configuration was to allow more-than-average-experienced user to seamlessly customize the app behevior.
Since you got a better concept of the preference GUI, the JSON will be used only by the backend as a config storage (and direct modification should be discouraged). I think that this will be better achieved by some packages like (https://www.npmjs.com/package/electron-config) https://www.npmjs.com/package/electron-store , specifically made with this purpose in mind.

**Comment by will-stone** [comment]
Ok, yes I like this idea.
Looks like store is the successor to config, so let's concentrate research there (https://github.com/sindresorhus/electron-store).

So now rather than syncing with a file, we just need a way to sync with the store. This should be fairly straight forward.

Also, browsers should probably remain as an array to maintain order, e.g.

```js
const browsers = [{...},{...},...]
store.set('browsers', browsers)
```

This also feels like we're doing it the _electron way_ as opposed to reinventing the wheel. Good find.

**Comment by Jackymancs4** [comment]
Some notes:
- As always, very bad commenting
- I don't like very much the actual approach, but given that I don't have much time to investigate the mutability of the Store object, I simply load the browsers list in memory, modify it, then save it to disk.
- I haven't figured out a comprehensive way to test the persistance of data.
- It works also after packaging

**Comment by will-stone** [comment]
Ok, I've carried on with what you started and created a rudimentary preferences window. It's still got a little way to go: https://github.com/will-stone/browserosaurus/tree/pr/17

It allows you to toggle Browsers but the pickerWindow's height isn't recalculated and the refresh is way to drastic (causing every browser to dissappear and reappear).

As for the pickerWindow, I'm thinking we pull out the tray creation, and then the picker can be destroyed and relaunched when the browsers' change (this should be so quick that the user won't know). As for the preferencesWindow, this will need nicer logic on how it detects when browsers have changed. Please take a look and let me know your thoughts. I can open a merge request to this branch if you're happy with the direction it's going.

**Comment by Jackymancs4** [comment]
I definetely like the direction it's going.
Right now (and now I'm really tired) my notes are:
- regarding the design, that's a draft of what I had in mind (everything but the colors): schermata 2017-12-13 alle 00 49 57 2 
A simple draggable list without icons, with shorter entries and actual html checkboxes.
This in order to create a visual differentiation with the picker, and also to be more practical (I think).
Also, my idea was about a Save/Cancel dynamic instead of save at every interaction. I would gladly discuss this one.
A personal note: your implementation of checkbox with '✔' is just awesome!

- About the code, yeah, the reload time of the preference window is just unbearable.
Deleting ```preferencesWindow.reload()``` in main.js:190 and and substituting 
```
listItem.addEventListener('click', () => {
      toggleBrowser(browser.name)
    })
```
with
```
listItem.addEventListener('click', (e) => {
      toggleBrowser(browser.name)
      e.target.classList.toggle('is-enabled')
    })
```
in preferencesRenderer.js seems to be a good (tested) fix.
Tomorrow I'll make a more comprehensive review.

**Comment by will-stone** [comment]
Good mockup, yes, let's aim for that. Last night I was simply trying to get something working before I went to sleep. The pickerRenderer (will need to rename renderer to this) is the window that needs its height updating, but yes, moving this logic to the renderer from main will help: we could get it to set height on each open. Just need to check the performance of this and make sure it doesn't make it flicker or anything like that. I'll have look into improving all of this later.

**Pull request merged**
