### PR TITLE
Linear.app

### PR DESCRIPTION
**Pull request by denisthemeanis**

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks @denisthemeanis Please fix the linting issues. Also, please confirm you have tested this on your machine and that it works with Linear app as you'd expect?

**Comment by denisthemeanis** [comment]
I have tested and it works as needed -
https://gyazo.com/e5f8449b490a5913bdfcc59ad3bab946

**Comment by will-stone** [comment]
Fantastic! And thanks for the video, that really makes it easier to accept in support for apps I don't use 🙂 I think the test will fail because the apps aren't in alphabetical order. If you'd like to fix this and rebase then please do. If you don't feel comfortable doing that, I can do it for you after merge.

**Comment by will-stone** [comment]
The apps need to be in alphabetical order by “name”. If you run npm test locally, this will help get this correct without needing to wait for CI results. Once you’ve fixed it, you happy to rebase your commits?

**Comment by will-stone** [comment]
Thanks @denisthemeanis this will be in the next release.

**Pull request merged**
