### PR TITLE
When double clicking on link, opens default browser

### PR DESCRIPTION
**Pull request by long-lazuli**
I make you a pull-request just as a proposition.

### CODE REVIEW

**Comment by will-stone** [comment]
Interesting idea. What happens if the clicked URL is in the center of the screen and therefore under a browser entry in the picker when it shows after the first click? If the answer to this is that we slow down the appearance of the picker window, and I can't think of any other way, then sadly I would not to implement it.

Once I've done a bit more refactoring, I hope to allow the changing of keyboard shortcuts. What this will mean is, say, a right handed user could click a link with the mouse and map their default browser to "z" or "space" or something else that's easy for them to reach.

After all, this is to replace the default browser. If a user gets into the habit of double clicking, then this app has become moot. We also don't want to encourage bad UX. Double clicking links is something I see our more senior members of society doing 😄 

I like all the ideas though, so don't let me get you down by closing all your suggestions. This project is MIT licenced, so feel free to fork/clone and go your own way. I only ask that if you release your creation, you brand it differently, new name, logo etc.

**Comment by long-lazuli** [comment]
Sorry to answer in a *closed-pr* !

I was a bit annoyed by the fact that the window could be above the link sometime. I had this concern before I saw your answer.

This is perfectly legit that you don't want to delay the window appearance.
But trying it this morning, I did really like the no-windows approach (and unfortunately dblclick, for now :( ).

So I did fork the app, and made some changes to suits my needs. I also renamed it, to be able to try both and see differences.
I would like you to let the credit for Browserosaurus in the README, 'cause this app inspired me changes I made.

You can find the changes here : https://github.com/long-lazuli/browsers.menu

In this fork, my goal is to remove the window completely, using just the tray menu.

Let's see where it goes.

I would like to be able to continue to swap ideas and code, if you don't mind :)  
So I let a branch up-to-date with your `master` and we'll see how far the differences can be.

I will focus on a "browser-chooser for devs", more than a "link opener".

**Comment by will-stone** [comment]
Awesome. Good luck in your endeavours. Remember to change the update checker to point to your new repo, and I’d appreciate it if you could change the logo and tray icon. No rush (and you are not legally abliged) but you will appreciate your work more if it has its own identity.

**Comment by long-lazuli** [comment]
sorry, what is the update checker ?

**Comment by will-stone** [comment]
In the about tab of the preferences window. Search the code for “update”.

**Pull request closed without merging**
