### PR TITLE
New App Listing: Spotify

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
Adding spotify to apps, this features makes it ables to open native
spotify app using spotify links.
More detail here #344

### CODE REVIEW

**Comment by tolgaerdonmez** [comment]
@will-stone I recreated the changes in the big-sur-branch like you've requested, also tested and it is working.

**Comment by tolgaerdonmez** [comment]
@will-stone 
also in the big sur branch, I could help. If you open issues then I could look up,whether I can achieve or not :)

**Comment by will-stone** [comment]
@tolgaerdonmez Thanks for your enthusiasm, however my redesigns can get a bit messy during development and I tend to make a lot of changes as I go along, so best just to wait for the next major release.

Thanks 😄

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez Thanks for your enthusiasm, however my redesigns can get a bit messy during development and I tend to make a lot of changes as I go along, so best just to wait for the next major release.
> 
> Thanks 😄 

then, wish you the best developing the next awesome design 😁

**Pull request merged**
