### PR TITLE
add Firefox Developer Edition

### PR DESCRIPTION
**Pull request by Jackymancs4**
Add Firefox Developer Edition.
Tested and working with FDE 57b14/58b1 on macOS 10.13.1

### CODE REVIEW

**Comment by Ornataweaver** [comment]
Instead of adding Browsers one by one, you can let the user choose the apps that list in Browserosaurus.
The name of your app is really hard to spell.

**Comment by will-stone** [comment]
Ha! Thanks, it also means it's the only result when Googled :)

Haven't we had this conversation before? https://github.com/will-stone/browserosaurus/issues/2

**Comment by Ornataweaver** [comment]
I know we had, but refreshing it might bring new point of views.
Watching a problem from different angles bring new insights. #Antichamber

**Comment by will-stone** [comment]
Yeah, I'm really not fussed spending the time figuring-out how to allow users to do this. Eventually we'll cover-off most browsers. It's not like new ones get released that often. I would like to let users remap the keyboard shortcuts at some point, but that's about it with regards to config in this area.

**Pull request merged**
