### PR TITLE
feat: add Opera Crypto

### PR DESCRIPTION
**Pull request by dn-l**
https://www.opera.com/crypto/next

### CODE REVIEW

**Comment by will-stone** [comment]
Hi @dn-l Thanks for the contribution. Can you please confirm you have run the change locally and B behaves as you'd expect?

**Comment by dn-l** [comment]
@will-stone yes
Screen Shot 2022-10-13 at 8 34 26

**Comment by dn-l** [comment]
@will-stone anything else I should check?

**Comment by will-stone** [comment]
Thanks @dn-l This will be in the next release.

**Pull request merged**
