### PR TITLE
Update support to current version of Brave and deprecate old

### PR DESCRIPTION
**Pull request by abuisman**
The newest version of the Brave browser is now called 'Brave Browser'. I have updated the activities and assigned the hotkey `b` to it. I have assigned the hotkey `z` to the older Brave browser version (called 'Brave') as a form of deprecation, as I think that people would want to use the most recent one as soon as possible anyway.

I have also copy pasted the old icon and renamed the copy in order for it to work properly.

### CODE REVIEW

**Comment by will-stone** [comment]
Nice. Thanks. However, I wouldn't bother with deprecation; anyone not updating Brave, probably isn't updating Browserosaurus.

**Comment by abuisman** [comment]
Glad to help.

True, although I have no idea how compatible the new version is with the old since they based the new one on Chromium if I am not mistaken. Therefore there could be a situation where people are living with both. No idea if this is true though as I just jumped on the new one from Vivaldi.

**Comment by will-stone** [comment]
Meh, I'd say we only support the latest version. Brave's website states:
> The Muon-based Brave browser is no longer available for download on our site
Therefore, let's ditch the old one. With the current implementation of Browserosaurus, where hotkeys are hard-coded, let's not sit on two for one browser. Thanks for the contribution. Are you a dev? If so, I'd appreciate it if you could please take a look at https://github.com/will-stone/browserosaurus/issues/77

**Comment by abuisman** [comment]
Oh well that sounds like deprecation is not needed. I'll fix it in a commit.

**Comment by abuisman** [comment]
@will-stone  oh and yes I am a dev, I saw it while browsing the issues. I'll have a closer look when I can. I am annoyed by this delay as well.

**Comment by will-stone** [comment]
Awesome! Thanks.

**Comment by silverbucket** [comment]
I've tested this on my Mac and it still isn't detecting the new Brave Browser, is there a trick to testing the code? I'm on a Mac and just changed the Application contents based on the diff, but not sure if that's all I need to do.

**Comment by will-stone** [comment]
@silverbucket try `rm -rf ~/Library/Application Support/Browserosaurus/config.json`

**Comment by silverbucket** [comment]
@will-stone Hmm, no that didn't seem to have any effect. Quit, deleted the config.json, ensured my changes were in the activities.js, and that the png was renamed to `Brave Browser.png`. Started it back up, rescanned, and it still doesn't show up.

**Comment by silverbucket** [comment]
It's definitely there though:


```
$ system_profiler -xml SPApplicationsDataType
...
<dict>
                                <key>_name</key>
                                <string>Brave Browser</string>
                                <key>has64BitIntelCode</key>
                                <string>yes</string>
                                <key>lastModified</key>
                                <date>2018-10-18T16:46:23Z</date>
                                <key>obtained_from</key>
                                <string>identified_developer</string>
                                <key>path</key>
                                <string>/Applications/Brave Browser.app</string>
                                <key>runtime_environment</key>
                                <string>arch_x86</string>
                                <key>signed_by</key>
                                <array>
                                        <string>Developer ID Application: Brave Software, Inc. (KL8N8XSYF4)</string>
                                        <string>Developer ID Certification Authority</string>
                                        <string>Apple Root CA</string>
                                </array>
                                <key>version</key>
                                <string>70.0.55.18</string>
                        </dict>
...
```

**Comment by silverbucket** [comment]
Also:

```
$ cat /Applications/Browserosaurus.app/Contents/Resources/app/src/config/activities.js
/**
 * Activities
 *
 */

export default [
  {
    appId: 'Brave-Browser-Dev',
    name: 'Brave Dev',
    hotKey: 'r',
    cmd: 'open "{URL}" -a Brave-Browser-Dev',
  },
  {
    appId: 'Brave Browser',
    name: 'Brave Browser',
    hotKey: 'b',
    cmd: 'open "{URL}" -a "Brave Browser"',
  },
  {
    appId: 'Chromium',
    name: 'Chromium',
    hotKey: 'c',
    cmd: 'open "{URL}" -a Chromium',
  },
...
```

**Comment by will-stone** [comment]
That’s the location of the built app’s config. Make it and try again. The dev’s config will be stored under the Electron app

**Comment by abuisman** [comment]
@silverbucket It worked fine for me on 2 different machines. When you start up the Electron version of Browserosaurus macos asks you if you want to switch the default browser to Electron from Browserosaurus, be sure to select Electron here. Did you do that?

**Comment by silverbucket** [comment]
Ah yeah, sorry, I was trying to modify my currently installed source. Re-building and installing the .dmg worked like a charm!

**Comment by silverbucket** [comment]
Will these be merged sometime soon?

**Pull request merged**
