### PR TITLE
Added open-in-background capability to Tor Browser

### PR DESCRIPTION
**Pull request by macgeekpro**

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks. Just to confirm, have you run the branch and seen this work with this browser?

**Comment by macgeekpro** [comment]
> Thanks. Just to confirm, have you run the branch and seen this work with this browser?

I have run the full command: `open` "{URL}" -a "Tor Browser" -g` in terminal and I can confirm it works.

**Comment by will-stone** [comment]
Cool. Can you please run the branch with your addition and confirm it works with Browserosaurus?

**Comment by macgeekpro** [comment]
> Cool. Can you please run the branch with your addition and confirm it works with Browserosaurus?

confirmed

**Pull request merged**
