### PR TITLE
Update Polypane icon

### PR DESCRIPTION
**Pull request by Kilian**
Polypane has a new icon, so updating this :)

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks. If you have a moment, could you see about adding yourself to the [browser logos project](https://github.com/alrra/browser-logos)?

**Comment by Kilian** [comment]
I could, but they weren't/aren't taking new chromium-based browsers: https://github.com/alrra/browser-logos/pull/173

I'll add a quick comment there to see if they can reconsider :)

**Comment by Kilian** [comment]
@will-stone ...I don't think they will. Are you ok with merging this instead? :)

**Comment by will-stone** [comment]
Of course, thanks for trying. I'll merge this now and will do a release soon (I'm not at my computer right now).

**Comment by Kilian** [comment]
Thanks @will-stone! No rush :)

**Pull request merged**
