### PR TITLE
feat: add support for Opera Developer

### PR DESCRIPTION
**Pull request by raccmonteiro**
feat: add support for Opera Developer

### CODE REVIEW

**Comment by will-stone** [comment]
Hi. Thanks for the update. Is it not that “Opera Dev” has been renamed? Or that it was never correct?

**Comment by raccmonteiro** [comment]
I believe it was rename. I didn't replace in case someone is using an older version. Do you think it can be replaced?

**Comment by raccmonteiro** [comment]
I found this article from 2014! https://techdows.com/2014/08/opera-developer-renamed-to-opera-developer.html 

But now, I don't know if it should be "Opera Developer" or "Opera developer". The installation path is "	/Applications/Opera Developer" 
image

**Comment by will-stone** [comment]
What's working when you spin up B locally?

**Comment by will-stone** [comment]
I'll just merge this in, doesn't matter if we have both spellings in there, the lookup is very quick now.

**Comment by raccmonteiro** [comment]
sorry, I went on holidays and not able no respond.
It's working with 'Opera Developer', thanks for merging

**Pull request merged**
