### PR TITLE
feat: add support for Slack

### PR DESCRIPTION
**Pull request by mathieutu**
And one again for slack (that I'll not introduce 😉)! 

BUT actually I'm seeing it doesn't work as Slack app seems to not be able to open its own links 🤦.
However it would work if we convert thier link to a `slack://` one. 

What would you think about replacing the `templateUrl` property by a `convertUrl` or something like that, which would be function that take an url and should give another?

I'm ok to do the PR.
Thanks.

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks for the test update, tell you what, please stick that in a different PR and we'll get that merged in now, as it'll help others with their submissions whilst we discuss the Slack integration.

So, Slack. Firstly, what's the scenario when you'd like Browserosaurus to open on a Slack link? Which app are you in? Describe it like I'm blind.

**Comment by mathieutu** [comment]
Here is an example (not the only one): 
My company has a paid slack workspace. We rely heavily on it, including to discuss and debate on topics.
We then open issues on Github, tickets on Linear, or even doc on Notion, and put the link to the debate so people can have all the context. 

I would like to open directly the link with slack instead of selecting a browser, then be redirected to slack.

I think it the same issue than https://github.com/will-stone/browserosaurus/issues/215.

Actually I made the convertUrl thing in local, and it works perfectly, and even more simply than the `templateUrl` property

Screenshot 2022-03-03 at 18 11 27
.

**Comment by mathieutu** [comment]
I've made the [PR](https://github.com/will-stone/browserosaurus/pull/510).

However I think we can't do anything for slack 😞.
The link we want to use is https://api.slack.com/reference/deep-linking#client__supported-uris__open-a-channel, but we don't have the app id in the initial uri, so we can't do anything without a api call.

**Comment by will-stone** [comment]
Ah, shall we close this down then? I'm not sure I feel comfortable with adding API calls, as it'll probably the user to setup tokens and the such.

**Comment by mathieutu** [comment]
Yep, agree with you. I'm [currently seeing that](https://twitter.com/mathieutu/status/1499447263634018313?s=20&t=4JcgEdsb4LBlUjUv6acdFQ) directly with slack

**Pull request closed without merging**
