### PR TITLE
(WIP)feat: profiles support

### PR DESCRIPTION
**Pull request by lemieszek**
## Issue
https://github.com/will-stone/browserosaurus/issues/56

## Screnshoots
image
image

## Bugs
- [ ] it creates new profiles instead of Default & Profile 1

## Missing
- [ ] should replace default chrome
- [ ] You should be able to keybind profiles
- [ ] You should be able to make profile favourite

### CODE REVIEW

**Comment by lemieszek** [comment]
🙈 just realized I mocked profiles on build time...

**Comment by huyz** [comment]
> 🙈 just realized I mocked profiles on build time...

What does that mean?

**Comment by lemieszek** [comment]
In my implementation I was gathering info about profiles on build time. So for end user it wouldn't be helpful at all.

**Comment by huyz** [comment]
Ok good to know. I guess that would still be useful to me.  Thanks!

**Pull request closed without merging**
