### PR TITLE
Reduced window reload needs to 0%

### PR DESCRIPTION
**Pull request by Jackymancs4**
Right now is not finished. It completely breaks the preference window, since I have not touched it yet.
The new architecture improve responsiveness and reduce startup time, (which can be further imprevod). It also delete all flickering effects that I know of. The rendering of the picker is very smooth, actually.
It is not tested when packaged.

### CODE REVIEW

**Comment by will-stone** [comment]
Ok. I'll get the prefs working again.

**Comment by will-stone** [comment]
Prefs now working again. It uses the global binding method. However it'll need to move to the webContents.send method as I intend to add a "rescan browsers" button, so a user doesn't need to restart the app if they add or remove a browser. Right, I think this piece of work is basically done. I'm going to go through and tidy it up with comments etc. Then we can look into reordering (there's probably a package out there that can help us with the drag/drop).

**Comment by Jackymancs4** [comment]
```
    findInstalledBrowsers().then(installedBrowsers => {
      pickerWindow.webContents.send('incomingBrowsers', installedBrowsers)
      preferencesWindow.webContents.send('incomingBrowsers', installedBrowsers)
    })
```
Was my idea for the rescan thing (maybe with a 5min timer). It's easy now.
I've almost fixed the prefs now, I'll PR soon.
I was wondering.. is it mandatory to destroy the preferences window every time?
Using the same hide/show thing that is used by the picker would be more smooth, I think.

**Comment by will-stone** [comment]
I’ve fixed the prefs. Yeah, I was wondering that about the prefs window. I’m not sure if it’s considered good form to have many windows loaded in the background. I suppose it’s only one more than we have now. Ok preload that one too. Definitely no timer please, I don’t want us causing a cpu spike every 5 minutes.

**Comment by Jackymancs4** [comment]
Can you push the prefs fix?

**Comment by will-stone** [comment]
It's in pr/17

**Comment by Jackymancs4** [comment]
Ohh, you mean 'fix: preferences not receiving installedBrowsers'? 
Because it's pretty broken to me.

**Comment by will-stone** [comment]
Please download branch pr/17 into a new folder, install dependencies and run it with `yarn start`, if still broken, please state exactly what is broken and if any errors show in terminal or console (if you're able to get to it with cmd-alt-I).

**Pull request merged**
