### PR TITLE
Adding Chrome Beta to the list of detected browsers

### LINKED ISSUE #361: [Feature Request] Add Chrome beta to the list of browsers detected
I looked at the list of current detected browsers and found Chrome canary but not beta - https://www.google.com/chrome/beta/

https://github.com/will-stone/browserosaurus/blob/master/src/config/apps.ts 

Can this be added to the list?

### PR DESCRIPTION
**Pull request by singhkays**
Fixes #361

### CODE REVIEW

**Comment by singhkays** [comment]
@will-stone I'm not a developer so don't completely understand the build failure. I know you are not taking feature requests but are you able to take a look to help get this merged?

**Comment by will-stone** [comment]
@singhkays No worries. Looks to be a failing test from before this PR. My bad. I'll fix it now...

**Comment by will-stone** [comment]
Thanks! I'll do a release now...

**Comment by singhkays** [comment]
Awesome! thank you

**Pull request merged**
