### PR TITLE
feat: add support for Figma Beta and Framer

### PR DESCRIPTION
**Pull request by HarshInvader**
Figma Beta and Framer are design tools that needed to be added.

### CODE REVIEW

**Comment by HarshInvader** [comment]
@will-stone Please review and merge, my design friends are waiting on this :)

**Comment by will-stone** [comment]
Hi @HarshInvader, thanks for the PR. Can you please confirm you have tested this locally (in particular Framer), and it opens the apps as you'd expect?

**Comment by HarshInvader** [comment]
> Hi @HarshInvader, thanks for the PR. Can you please confirm you have tested this locally (in particular Framer), and it opens the apps as you'd expect?

Hey sorry for the late reply. Yes it does! Working as expected locally :)

**Comment by will-stone** [comment]
Thanks! This will be in the next release.

**Pull request merged**
