### PR TITLE
feat: Add support for FreeTube

### PR DESCRIPTION
**Pull request by sonalder-darlene**
FreeTube is a YouTube client for Windows, Mac, and Linux built around using YouTube more privately. You can enjoy your favorite content and creators without your habits being tracked. All of your user data is stored locally and never sent or published to the internet. FreeTube grabs data by scraping the information it needs (with either local methods or by optionally utilizing the Invidious API). With many features similar to YouTube, FreeTube has become one of the best methods to watch YouTube privately on desktop.
Description from https://freetubeapp.io/

### CODE REVIEW

**Comment by will-stone** [comment]
Hi 👋 Thanks for the contribution. Please confirm you have run Browserosaurus locally with your changes and it behaves as you’d like expect when attempting to open a link with the new browser?

**Comment by sonalder-darlene** [comment]
I run the test with no issue but when I've tried to open my build locally I got on Electron page telling me to run $ null path-to-app in the command line which does nothing. I've put it as my default browser but when I wanted to open a link it opened that Electron page. Never used Electron and don't know how to do. But I could set up a key for FreeTube and saw the logo in the menu bar.
How can I do for the electron to strat locally. The terminal always tell me : command not found : null

**Comment by will-stone** [comment]
Hi @sonalder-darlene Have you followed the [setting up for development](https://github.com/will-stone/browserosaurus/blob/main/docs/setting-up-for-development.md) documentation? No worries if it's not working, I'll release it and then you'll see if it's working. Can you please just fix the lint warning and use a 128x128 image file. Thanks.

**Comment by sonalder-darlene** [comment]
Yes I've done the setup

I've downgrade the logo to 128x and have no more warning... I think

**Comment by will-stone** [comment]
Thanks, this will be in the next release.

**Comment by sonalder-darlene** [comment]
I can confirm that it's working perfectly ^^

**Pull request merged**
