### PR TITLE
feat: add support for Miro

### PR DESCRIPTION
**Pull request by splagemann**
This adds support for the Miro desktop app

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks @splagemann Please confirm you have built and run this locally and Browserosaurus sends URLs to Miro as you expect?

**Comment by splagemann** [comment]
I've tested it locally, but apparently I didn't run `npm test` 🙈

**Comment by splagemann** [comment]
@will-stone should be good to go now

**Comment by will-stone** [comment]
Thank you @splagemann This will be in the next release 😎

**Pull request merged**
