### PR TITLE
Adding support for the Orion Browser

### PR DESCRIPTION
**Pull request by FluffyKitty776**
This pull request is to add support for the Orion Browser on MacOS platforms.

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks, well if you're already using the released version of B on macOS 12 then that's a good sign 🙂 

Are you following this guide? https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md

On a side-note, I'd never heard of Orion or Kagi before your PR. I looked it all up and I'm certainly interested in the search engine now! I've signed-up for the beta but not heard back yet. I use Brave Search at the moment, which is great but feels like it's just not _quite_ fast enough yet. Are you using Kagi search? Any good? Also, any idea how to pronounce it? 😆

**Comment by will-stone** [comment]
Hmmm 🤔 Which version of node are you using?

**Comment by FluffyKitty776** [comment]
I am using node 7.24.2, it is the only version I could get working on the MacOS 12 Public Beta.

**Comment by will-stone** [comment]
[This issue](https://github.com/facebook/react-native/issues/21038) on another repo is littered with people saying that rebooting and/or re-running `npm install` seems to do the trick 😕

**Comment by FluffyKitty776** [comment]
Now I got as far as this after a reboot (Seems like that fixed the error) but I do not know what electron-prebuilt-compile is, lol
```bash
MacBook-Air:browserosaurus rawr$ npm run make:arm

> browserosaurus@15.2.1 make:arm
> electron-forge make --skip-package --arch=arm64

✔ Checking your system
✖ Resolving Forge Config

Electron forge was terminated:
You must depend on "electron-prebuilt-compile" in your devDependencies
```

**Comment by will-stone** [comment]
That's odd, I have an M1 and use it in from and non-emulated terminal 🤷‍♂️ Anyway, thank you for testing it.

Looks like you've got some linting errors in there.

**Comment by will-stone** [comment]
They need to be grouped. Try running `npm run lint -- --fix`. It should have done all this for you when you committed using a pre-commit hook. Strange.

**Comment by will-stone** [comment]
Thanks @FluffyKitty776 This will be in the next release.

**Pull request merged**
