### PR TITLE
Add Finicky to whitelist and logo to logos directory.

### PR DESCRIPTION
**Pull request by anmull**
Going ahead and fixing #249 while working on #250.

### CODE REVIEW

**Comment by anmull** [comment]
Logo has been optimized with ImageOptim.app

**Comment by will-stone** [comment]
Thanks! It looks like the checks have got stuck but hopefully they will timeout sometime soon 🤷‍♂️

**Comment by will-stone** [comment]
Ahhh... I'm just gonna turn the checks off. I don't know why they fail auth when I have the FontAwesome license saved as a secret and it works on my branches 🙄

**Comment by will-stone** [comment]
I don't think any of the icons I use are Pro icons, anyway. I think I just like the idea of being able to use them because I pay for them, and the upcoming v6 icons look nice. I've emailed their support for help. Hopefully, they can provide a solution for contributors.

**Pull request merged**
