### PR TITLE
New App Listing: Spotify

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
Normally spotify uri's won't open in the native app, this commit fixes
that

### CODE REVIEW

**Comment by tolgaerdonmez** [comment]
I've just added the spotify app to the browsers' list, but if this feature is okay with you @will-stone  I can also create and statement, whether to the link is for spotify, then show spotify in the Tiles, if not don't show spotify. I believe this would be a better approach because no one wants to see spotify in a browser list

**Comment by will-stone** [comment]
Hi. Thanks for the PR.

1. Could you please give me the use case for this?
2. Could you please give me an example of a URL that you would want to send to Spotify?
2. What happens if any other URL is sent to Spotify?

**Comment by tolgaerdonmez** [comment]
1. Like I said, the native Spotify macos app doesn't catch spotify links and the user cannot open spotify links in spotify app. 

When clicking a Spotify, song, playlist, etc. url like in the screenshot below
Screen Shot 2020-12-08 at 11 52 42

Then it opens the song, playlist etc. in spotify's native macos app
Screen Shot 2020-12-08 at 11 56 36

2. The URL I used in the example above: (https://open.spotify.com/track/7vFGzP82IzNbNz2CSEQHUs?si=eBb_gCV4QZ29QuIqGdn66Q)


3. If an invalid link goes to Spotify, nothing happens.

**Comment by will-stone** [comment]
Nice! Sounds good to me 😄 

Leave the logic as is, as users can always hide Spotify from Browserosaurus in the settings menu.

This will definitely get merged, however I'm in the middle of a design-update in the `big-sur-design` branch, in fact, do you mind pointing this PR at that branch?

I also bought an M1 laptop so I'm trying to make it run well with that. Therefore it may be a while until this gets released, or it could be very soon, it all depends how it goes, and thus is the world of open source 🤓

**Comment by tolgaerdonmez** [comment]
> Nice! Sounds good to me 😄
> 
> Leave the logic as is, as users can always hide Spotify from Browserosaurus in the settings menu.
> 
> This will definitely get merged, however I'm in the middle of a design-update in the `big-sur-design` branch, in fact, do you mind pointing this PR at that branch?
> 
> I also bought an M1 laptop so I'm trying to make it run well with that. Therefore it may be a while until this gets released, or it could be very soon, it all depends how it goes, and thus is the world of open source 🤓

Happy to hear that, I'll be pointing that to that branch. 
❤️ OSS

**Comment by tolgaerdonmez** [comment]
@will-stone I'm currently unable to run big-sur-design branch on macos big sur? Is it only for M1 laptops.

This is the error I'm getting

Screen Shot 2020-12-08 at 12 25 03

**Comment by will-stone** [comment]
Re-pull and delete your node_modules and then `yarn` again. Should work.

**Comment by will-stone** [comment]
This will go into Big Sur branch. Closing

**Pull request closed without merging**
